[package]
name = "table"
version = "0.1.0"
authors = ["Kyle Clemens <git@kyleclemens.com>"]

[dependencies]
serde = "1"
rmp-serde = "0.13"
failure = "0.1"
failure_derive = "0.1"

[dev-dependencies]
serde_derive = "1"
